version: "3.8"  # Gunakan versi 2 ke atas

services:
  item-db:
    image: mongo:3
    container_name: item-db
    volumes:
      - app-db:/data/db

  item-app:
    image: item-app:v1
    container_name: item-app
    ports:
      - "80:8080"
    depends_on:
      - item-db
    environment:
      - NODE_ENV=production
      - DB_HOST=item-db

volumes:
  app-db:
